config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users
  root to: 'words#new'

  resources :word_types
  get 'words/rate' => 'words#rate', as: 'rate_word'
  delete 'words/destroy_all' => 'words#destroy_all', as: 'destroy_all_words'
  get 'words/:id/rate' => 'words#save_rating', as: 'save_word_rating'

  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/word_types_controller.rb
class WordTypesController < ApplicationController
  before_action :set_word_type, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @word_types = WordType.all
  end

  def show
  end

  def new
    @word_type = WordType.new
  end

  def edit
  end

  def create
    @word_type = WordType.new(word_type_params)

    if @word_type.save
      redirect_to word_types_url, notice: 'Word type was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @word_type.update(word_type_params)
        format.html {redirect_to @word_type, notice: 'Word type was successfully updated.'}
        format.json {render :show, status: :ok, location: @word_type}
      else
        format.html {render :edit}
        format.json {render json: @word_type.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @word_type.destroy
    respond_to do |format|
      format.html {redirect_to word_types_url, notice: 'Word type was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  def set_word_type
    @word_type = WordType.find(params[:id])
  end

  def word_type_params
    params.require(:word_type).permit(:key, :name, :description)
  end
end

app/helpers/word_types_helper.rb
module WordTypesHelper
end

app/views/word_types/_form.html.erb
<%= form_with(model: word_type, local: true) do |form| %>
  <%= render 'common/form_errors', resource: word_type %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :word_type_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :key %>
    <%= form.text_field :key, id: :word_type_key, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :word_type_key, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit nil, {class: 'btn btn-light'} %>
  </div>
<% end %>

app/views/word_types/edit.html.erb
<h1>Editing Word Type</h1>

<%= render 'form', word_type: @word_type %>

<%= link_to 'Show', @word_type %> |
<%= link_to 'Back', word_types_path %>

app/views/word_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Word Types</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Key</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @word_types.each do |word_type| %>
    <tr>
      <td><%= word_type.name %></td>
      <td>{!<%= word_type.key %>}</td>
      <td>
        <%= link_to fa_icon('eye'), word_type, class: 'btn btn-light' %>
        <%= link_to fa_icon('pencil-square-o'), edit_word_type_path(word_type), class: 'btn btn-light' %>
        <%= link_to fa_icon('trash-o'), word_type, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-light' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word Type', new_word_type_path, class: 'btn btn-radius btn-light' %>

app/views/word_types/new.html.erb
<h1>New Word Type</h1>

<%= render 'form', word_type: @word_type %>

app/views/word_types/show.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h4 class="card-title"><%= @word_type.name %></h4>
    <div class="card-text">
      <p>
        <strong>{!<%= @word_type.key %>}</strong>
      </p>

      <div class="row">
        <div class="col">
          <% if can?(:edit, WordType) %>
            <%= link_to 'Edit', edit_word_type_path(@word_type), class: 'btn btn-outline-dark' %>
          <% end %>
          <%= link_to 'All Word Types', word_types_path, class: 'btn btn-outline-dark card-link' %>
        </div>
      </div>
      <br>
      <h4>Words</h4>
      <table class="table table-sm">
        <thead>
        <tr>
          <th>Word</th>
          <th>Date</th>
          <th>User</th>
        </tr>
        </thead>
        <tbody>
        <% @word_type.words.order(created_at: :desc).each do |word| %>
          <tr>
            <td><%= word.value %></td>
            <td><%= word.created_at.strftime("%m-%d-%y %l:%M %P") %></td>
            <td><%= word&.user&.email %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>