config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users
  root to: 'words#new'

  resources :word_types
  get 'words/rate' => 'words#rate', as: 'rate_word'
  delete 'words/destroy_all' => 'words#destroy_all', as: 'destroy_all_words'
  get 'words/:id/rate' => 'words#save_rating', as: 'save_word_rating'

  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord

  def body_with_words
    if @body_with_words.nil?
      @body_with_words = self.body.clone
      matches = @body_with_words.scan(/\{!(.+?)\}/) unless self.body.nil?

      # Check matches against built in variables
      matches&.each do |match|
        match = match.first
        if match.include?(':')
          splits = match.split(':')
          global = splits[1]
          match = splits[0]
        end

        word_type = WordType.where(key: match).first
        word = word_type&.get_random_word
        next if word.nil?
        value = word&.value
        value ||= ''
        value = add_word_data(word_type, word, value)
        if global.present?
          @body_with_words.gsub!(/{!#{match}:#{global}}/i, value)
        else
          @body_with_words.sub!(/{!#{match}}/i, value)
        end
      end
    end
    @body_with_words
  end

  private

  def add_word_data(word_type, word, value)
    text = "word type: #{CGI::escapeHTML(word_type.name)}<br>user: #{CGI::escapeHTML(word.user&.email)}"
    value = "<span class='replacement toolpop' data-toggle='popover' data-trigger='click' title='Word Info' data-content=\"#{text}\">#{value}</span>" unless value.blank?
    value
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @stories = Story.all
  end

  def show
  end

  def new
    @story = Story.new
  end

  def edit
  end

  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:name, :body)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <%= render 'common/form_errors', resource: story %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :story_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :story_body, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.submit nil, {class: 'btn btn-light'} %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>
<%= link_to 'Read', @story, class: 'btn btn-outline-light' %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @stories.each do |story| %>
    <tr>
      <td><%= story.name %></td>
      <td>
        <%= link_to fa_icon('eye'), story, class: 'btn btn-light' %>
        <% if can?(:edit, Story) %>
          <%= link_to fa_icon('pencil-square-o'), edit_story_path(story), class: 'btn btn-light' %>
        <% end %>
        <% if can?(:destroy, Story) %>
          <%= link_to fa_icon('trash-o'), story, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-light' %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path, class: 'btn btn-light' %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h4 class="card-title"><%= @story.name %></h4>
    <p class="card-text">
      <%= @story.body_with_words.gsub("\n", '<br>').html_safe %>
    </p>
    <% if can?(:edit, Story) %>
      <%= link_to 'Edit', edit_story_path(@story), class: 'btn btn-outline-dark card-link' %>
    <% end %>
    <%= link_to 'All Stories', stories_path, class: 'btn btn-outline-dark card-link' %>
  </div>
</div>