config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users
  root to: 'words#new'

  resources :word_types
  get 'words/rate' => 'words#rate', as: 'rate_word'
  delete 'words/destroy_all' => 'words#destroy_all', as: 'destroy_all_words'
  get 'words/:id/rate' => 'words#save_rating', as: 'save_word_rating'

  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :word_type
  belongs_to :user
  has_many :word_ratings, dependent: :delete_all

  DOWNVOTE_THRESHOLD = 2

  validates_presence_of :value, :user_id, :word_type_id
  validates :value, uniqueness: {case_sensitive: false, scope: :word_type_id}

  scope :down_votes, -> (word_id) {joins(:word_ratings).where(word_ratings: {word_id: word_id, rating: -1})}
  scope :up_votes, -> (word_id) {joins(:word_ratings).where(word_ratings: {word_id: word_id, rating: 1})}
  scope :skips, -> (word_id) {joins(:word_ratings).where(word_ratings: {word_id: word_id, rating: 0})}

  def check_ratings
    if self.word_ratings.where(rating: -1).count >= DOWNVOTE_THRESHOLD
      self.destroy
    end
  end

  def down_votes
    self.class.down_votes(self.id)
  end

  def up_votes
    self.class.up_votes(self.id)
  end

  def skips
    self.class.skips(self.id)
  end
end

app/models/word_type.rb
class WordType < ApplicationRecord
  has_many :words, dependent: :delete_all

  validates :key, uniqueness: {case_sensitive: false}
  validates :name, uniqueness: {case_sensitive: false}

  def get_random_word
    Word.uncached do
      self.words.order("RANDOM()").first
    end
  end

  def self.choose_needed
    word_types = self.all.joins('LEFT JOIN words on words.word_type_id = word_types.id').
        select('word_types.*, COUNT(words.id)').
        group('word_types.id').
        order('count ASC').limit(3)
    word_types.shuffle.first
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy, :save_rating]
  load_and_authorize_resource

  def index
    @words = Word.accessible_by(current_ability).order(created_at: :desc)
  end

  def show
  end

  def rate
    voted_for = WordRating.where(user_id: current_user.id).pluck(:word_id)
    @word = Word.joins('LEFT JOIN word_ratings ON word_ratings.word_id = words.id').
        where.not(user_id: current_user.id).
        where.not(words: {id: voted_for}).
        select('words.*, COUNT(word_ratings.id)').group('words.id').
        order('count ASC').limit(6).shuffle.first
    @word_type = @word.word_type if @word
  end

  def save_rating
    WordRating.create(user_id: current_user.id, word_id: @word.id, rating: params[:rating])
    redirect_to rate_word_path
  end

  def new
    @word = Word.new
    @word_type = WordType.choose_needed
    @word.word_type_id = @word_type&.id
  end

  def edit
  end

  def create
    @word = Word.new(word_params)
    @word.user_id = current_user.id

    unless @word.save
      flash[:danger] = @word.errors.full_messages.join(' ')
    end
    redirect_to new_word_path
  end

  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html {redirect_to @word, notice: 'Word was successfully updated.'}
        format.json {render :show, status: :ok, location: @word}
      else
        format.html {render :edit}
        format.json {render json: @word.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @word.destroy
    respond_to do |format|
      format.html {redirect_to words_url, notice: 'Word was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def destroy_all
    Word.destroy_all
    redirect_to words_url, notice: 'Words were successfully destroyed.'
  end

  private
  def set_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(:value, :word_type_id)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<% unless @word.persisted? %>
  <div class="row">
    <div class="col">
      <h5><%= @word_type.name %></h5>
      <% if @word_type.description.present? %>
        <p><%= @word_type.description %></p>
      <% end %>
    </div>
  </div>
<% end %>

<%= form_with(model: word, local: true) do |form| %>
  <%= render 'common/form_errors', resource: word %>

  <div class="form-group">
    <%= form.text_field :value, id: :word_value, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :word_type_id %>
    <%= form.submit nil, {class: 'btn btn-light'} %>
    <%= link_to 'Skip', new_word_path, {class: 'btn btn-outline-light'} %>
  </div>

  <div class="form-group">
    <%= link_to 'Rate Words', rate_word_path, {class: 'btn btn-outline-light'} %>
    <% if can?(:edit, Word) %>
      <%= link_to 'All Words', words_path, {class: 'btn btn-outline-light'} %>
    <% end %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table class="table">
  <thead>
  <tr>
    <th>Value</th>
    <th>Word type</th>
    <th><%= fa_icon('thumbs-o-down') %></th>
    <th><%= fa_icon('thumbs-o-up') %></th>
    <th><%= fa_icon('question') %></th>
    <th>User</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @words.each do |word| %>
    <tr>
      <td><%= word.value %></td>
      <td><%= word.word_type&.name %></td>
      <td><%= word.down_votes.count %></td>
      <td><%= word.up_votes.count %></td>
      <td><%= word.skips.count %></td>
      <td><%= word.user&.email %></td>
      <td>
        <%= link_to fa_icon('eye'), word, class: 'btn btn-light' %>
        <%= link_to fa_icon('pencil-square-o'), edit_word_path(word), class: 'btn btn-light' %>
        <%= link_to fa_icon('trash-o'), word, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-light' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path, class: 'btn btn-light' %>
<%= link_to 'Delete All Words', destroy_all_words_path, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>

app/views/words/new.html.erb
<% if @word_type %>

  <%= render 'form', word: @word %>

<% else %>
  <div class="alert alert-warning" role="alert">
    No Word Types found, please add some first.
  </div>
<% end %>

app/views/words/rate.html.erb
<% if @word %>
  <div class="row">
    <div class="col">
      <h3><%= @word.value %></h3>
      <p>
        ... is this word a "<b><%= @word_type.name %></b>"?
      </p>
      <p><%= @word_type.description %></p>
    </div>
  </div>
  <div class="form-group">

    <%= link_to fa_icon('thumbs-o-up'), save_word_rating_path(@word, rating: 1), {class: 'btn btn-light'} %>
    <%= link_to 'Not Sure', save_word_rating_path(@word, rating: 0), {class: 'btn btn-light'} %>
    <%= link_to fa_icon('thumbs-o-down'), save_word_rating_path(@word, rating: -1), {class: 'btn btn-light'} %>
  </div>


<% else %>
  <div class="alert alert-success" role="alert">
    No more words to rate!
  </div>
<% end %>

<div class="form-group">
  <%= link_to 'Add Words', new_word_path, {class: 'btn btn-outline-light'} %>
</div>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @word.value %>
</p>

<p>
  <strong>User:</strong>
  <%= @word.user_id %>
</p>

<p>
  <strong>Down votes:</strong>
  <%= @word.down_votes %>
</p>

<p>
  <strong>Up votes:</strong>
  <%= @word.up_votes %>
</p>

<p>
  <strong>Word type:</strong>
  <%= @word.word_type_id %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>