config/routes.rb
Rails.application.routes.draw do
  resources :stories
  devise_for :users
  root to: 'words#new'

  resources :word_types
  get 'words/rate' => 'words#rate', as: 'rate_word'
  delete 'words/destroy_all' => 'words#destroy_all', as: 'destroy_all_words'
  get 'words/:id/rate' => 'words#save_rating', as: 'save_word_rating'

  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Mad Libs</a>

  <% if signed_in? %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <% if can? :read, WordType %>
          <li class="nav-item">
            <%= link_to 'Word Types', word_types_path, class: 'nav-link' %>
          </li>
        <% end %>
        <% if can? :read, Word %>
          <li class="nav-item">
            <%= link_to 'Words', new_word_path, class: 'nav-link' %>
          </li>
        <% end %>
        <% if can? :read, Story %>
          <li class="nav-item">
            <%= link_to 'Stories', stories_path, class: 'nav-link' %>
          </li>
        <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to('Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
          </div>
        </li>

      </ul>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Hello, world!</title>
  <%= csrf_meta_tags %>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <style>
    body {
      font: 20px Montserrat, sans-serif;
      line-height: 1.8;
      color: #f5f6f7;
    }

    p {
      font-size: 16px;
    }

    .margin {
      margin-bottom: 45px;
    }

    .bg-1 {
      background-color: #1abc9c; /* Green */
      color: #ffffff;
    }

    .bg-2 {
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
    }

    .bg-3 {
      background-color: #ffffff; /* White */
      color: #555555;
    }

    .bg-4 {
      background-color: #2f2f2f; /* Black Gray */
      color: #fff;
    }

    .container-fluid {
      padding-top: 70px;
      padding-bottom: 70px;
    }

    .navbar {
      padding-top: 15px;
      padding-bottom: 15px;
      border: 0;
      border-radius: 0;
      margin-bottom: 0;
      font-size: 12px;
      letter-spacing: 5px;
    }

    .navbar-nav li a:hover {
      color: #1abc9c !important;
    }
  </style>

</head>
<body class="bg-1">
<%= render 'layouts/navigation' %>

<div class="container-fluid">

  <%= render 'common/flash_messages' %>

  <div class="row">
    <div class="col">
      <%= yield %>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p>Copyright <%= Date.today.year %> Sean Mikkelsen</p>
</footer>
</body>
</html>